#KAFKA
BOOTSTRAP_SERVERS = ""
SECURITY_PROTOCOL = ""
SASL_MECHANISMS = ""
SASL_USERNAME = ""
SASL_PASSWORD = ""
SESSION_TIMEOUT_MS = ""
CLIENT_ID = ""

#AWS
ACCESS_KEY = ''
SECRET_KEY = ''
REGION_NAME = ''